name: build-and-deploy
# Only run when master is pushed.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: |
          npm install
      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        # Build locally first to make sure it works.
        run: |
          npm run build
          tar cf deploy.tar package.json package-lock.json pnpm-lock.yaml postcss.config.cjs tailwind.config.ts src static svelte.config.js tsconfig.json vite.config.ts Dockerfile captain-definition
      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
